### ISSUE TITLE
Clean-up Setup Page

### ISSUE THREAD

**Issue by ndalyrose** [data-lessons/library-git#35]
Need to enhance the setup page so it includes more complete instructions so that it can stand alone. References to other weeks without links too confusing.   http://data-lessons.github.io/library-git/setup/ @alexandermendes wanna have a go?

**Comment by alexandermendes** [comment]
Sure, I think it can probably just be replaced with something very simple, for example:

1. Create a GitHub account 
2. Install git
3. Configure git

**Comment by evanwill** [comment]
One issue that will come up is that the lesson references using `nano`, which is not typically installed on Windows (Git Bash doesn't have it). 

SWC had a Windows installer that added nano to Git Bash, but there has been a big discussion to replace the installer since it isn't really maintained. Others just say to use any text editor, but unfortunately I have found people don't usually have one (other than Notepad, which isn't very appropriate since it can't handle unix line endings and encodings).  

So I guess my question is there a central Lib Carpentry setup where we say get a text editor, get a terminal set up, etc? Or do we have to add all the necessities to this lesson?

for ref: SWC carpentry has initial set up as part of the main [workshop page](http://swcarpentry.github.io/workshop-template/), then each lesson has a very basic [set up page](http://swcarpentry.github.io/git-novice/setup/) since everything is already installed.

**Comment by alexandermendes** [comment]
Yeah I agree about the nano references. In fact, there are some inconsistencies throughout the lessons regarding recommended text editors (I've also spotted vim somewhere).

But in reality, if people start using git are they really going to want to make changes using such tools? I don't!

I think it might be handy to let people know they can edit files in any text editor, as they normally would, although I do see your point about what appropriate ones to recommend.

What about [Atom](https://atom.io/)? I haven't really tried it yet but looks interesting. Although again it's difficult to know if this is more or less intimidating that nano/vim etc.

**Comment by alexandermendes** [comment]
Scrap the Atom idea actually, just another thing to setup. But yes, whatever we choose should possibly be addressed in the setup. And let's hope that everyone can manage to open Powershell or a Unix terminal!

**Comment by kirschbombe** [comment]
I like the idea of having one initial setup page, with a setup section for each lesson that references the bits needed for that lesson. For example, if the main setup page has instructions for Git, text editors, python, etc., then the Git lesson setup section would just point folks to the Git and text editor parts of that doc. 

Also, I think most people find editors like Atom and Sublime more intuitive than nano and wouldn't want to dismiss the idea of adding these as option in setup. 

Here's a link to instructions on associating a text editor with Git: https://help.github.com/articles/associating-text-editors-with-git/
